# Generated by Django 6.0.7 on 2026-08-31 05:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_flow_app', '0002_printer_printjob_printer'),
    ]

    operations = [
        migrations.CreateModel(
            name='DarajaConfiguration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('environment', models.CharField(choices=[('sandbox', 'Sandbox'), ('production', 'Production')], default='sandbox', max_length=20)),
                ('consumer_key', models.CharField(max_length=255)),
                ('consumer_secret', models.CharField(max_length=255)),
                ('passkey', models.CharField(max_length=255)),
                ('short_code', models.CharField(max_length=50)),
                ('callback_url', models.URLField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('last_verified_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='daraja_configuration', to='print_flow_app.tenant')),
            ],
        ),
        migrations.CreateModel(
            name='Pricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('paper_size', models.CharField(choices=[('A4', 'A4'), ('A3', 'A3'), ('A5', 'A5'), ('LETTER', 'Letter'), ('LEGAL', 'Legal')], default='A4', max_length=20)),
                ('print_type', models.CharField(choices=[('black_white', 'Black & White'), ('color', 'Color')], default='black_white', max_length=20)),
                ('sides', models.CharField(choices=[('single', 'Single-Sided'), ('double', 'Double-Sided')], default='single', max_length=20)),
                ('price_per_page', models.DecimalField(decimal_places=2, max_digits=10)),
                ('minimum_charge', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pricing', to='print_flow_app.tenant')),
            ],
            options={
                'ordering': ['paper_size', 'print_type', 'sides'],
                'constraints': [models.UniqueConstraint(fields=('tenant', 'paper_size', 'print_type', 'sides'), name='unique_tenant_print_pricing')],
            },
        ),
    ]
