# Generated by Django 6.0.7 on 2026-07-22 20:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_flow_app', '0002_document_printjob_payment'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='cloudinary_public_id',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='document',
            name='cloudinary_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='document',
            name='mime_type',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='document',
            name='pages',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=20),
        ),
    ]
