# Generated by Django 6.0.7 on 2026-07-23 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_flow_app', '0003_document_cloudinary_public_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='color_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='paper_charge',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='payment',
            name='subtotal',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
            preserve_default=False,
        ),
    ]
