# Generated by Django 6.0.7 on 2026-09-01 05:56

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_flow_app', '0003_darajaconfiguration_pricing'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='price',
            new_name='monthly_price',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='billing_cycle',
        ),
        migrations.AddField(
            model_name='plan',
            name='yearly_price',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10),
        ),
    ]
