# Generated by Django 6.0.7 on 2026-09-01 11:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_flow_app', '0005_subscription_billing_cycle'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerTenantMembership',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('active', 'Active'), ('blocked', 'Blocked'), ('inactive', 'Inactive')], default='active', max_length=20)),
                ('joined_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tenant_memberships', to=settings.AUTH_USER_MODEL)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_memberships', to='print_flow_app.tenant')),
            ],
            options={
                'indexes': [models.Index(fields=['tenant', 'status'], name='print_flow__tenant__0f5c4a_idx'), models.Index(fields=['customer', 'status'], name='print_flow__custome_58d601_idx')],
                'constraints': [models.UniqueConstraint(fields=('customer', 'tenant'), name='unique_customer_tenant_membership')],
            },
        ),
    ]
