# Generated by Django 6.0.7 on 2026-08-04 22:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_flow_app', '0005_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='cloudinary_public_id',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='document',
            name='mime_type',
            field=models.CharField(blank=True, max_length=500),
        ),
        migrations.AlterField(
            model_name='document',
            name='original_name',
            field=models.CharField(max_length=500),
        ),
    ]
