# Generated by Django 6.0.7 on 2026-08-04 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_flow_app', '0006_alter_document_cloudinary_public_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='document',
            name='file',
            field=models.FileField(blank=True, max_length=500, null=True, upload_to='documents/'),
        ),
    ]
