# Generated by Django 6.0.7 on 2026-09-03 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_flow_app', '0007_printagent'),
    ]

    operations = [
        migrations.AddField(
            model_name='printjob',
            name='print_agent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='print_jobs', to='print_flow_app.printagent'),
        ),
    ]
