# Generated by Django 6.0.7 on 2026-09-03 07:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_flow_app', '0008_printjob_print_agent'),
    ]

    operations = [
        migrations.AddField(
            model_name='printer',
            name='local_printer_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
