# Generated by Django 6.0.7 on 2026-09-06 07:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('print_flow_app', '0010_discoveredprinter'),
    ]

    operations = [
        migrations.AddField(
            model_name='subscriptionpayment',
            name='billing_cycle',
            field=models.CharField(blank=True, choices=[('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='subscriptionpayment',
            name='pending_plan',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pending_subscription_payments', to='print_flow_app.plan'),
        ),
    ]
